name: Checks

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    if: (github.event_name == 'schedule' && github.repository == 'Taishi-N324/task_loss') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U black==24.10.0 blackdoc==0.3.9

    - name: black
      run: black . --check --diff

    - name: blackdoc
      run: blackdoc . --check --diff